/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.conversao;

import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGrafica
     */
    public InterfaceGrafica() {
        initComponents();
    }
    
    //public Moeda[] moedas = {new Euro(), new Dolar(), new Real()};
    public Moeda moedaOrigem = null;
    public Moeda moedaDestino = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        moedaOrigemCB = new javax.swing.JComboBox<>();
        moedaDestinoCB = new javax.swing.JComboBox<>();
        valorTF = new javax.swing.JTextField();
        converterBT = new javax.swing.JButton();
        resultadoTF1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moedaOrigemCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Real", "Dólar", "Euro" }));
        moedaOrigemCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moedaOrigemCBActionPerformed(evt);
            }
        });

        moedaDestinoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Real", "Dólar", "Euro" }));
        moedaDestinoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moedaDestinoCBActionPerformed(evt);
            }
        });

        valorTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTFActionPerformed(evt);
            }
        });

        converterBT.setText("Converter");
        converterBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterBTActionPerformed(evt);
            }
        });

        resultadoTF1.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(moedaOrigemCB, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moedaDestinoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultadoTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(converterBT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moedaOrigemCB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moedaDestinoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(valorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(converterBT)
                .addGap(18, 18, 18)
                .addComponent(resultadoTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moedaDestinoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moedaDestinoCBActionPerformed
        if(moedaDestinoCB.getSelectedItem().toString().equals("Real")){
            moedaDestino = new Real();
        }
        if(moedaDestinoCB.getSelectedItem().toString().equals("Dólar")){
            moedaDestino = new Dolar();
        }
        if(moedaDestinoCB.getSelectedItem().toString().equals("Euro ")){
            moedaDestino = new Euro();
        }
        if(moedaDestinoCB.getSelectedItem().toString().equals("<Selecione>")){
            JOptionPane.showMessageDialog(rootPane, "Você deve selecionar uma moeda", "Selecione uma moeda", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_moedaDestinoCBActionPerformed

    private void moedaOrigemCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moedaOrigemCBActionPerformed
        if(moedaOrigemCB.getSelectedItem().toString().equals("Real")){
            moedaOrigem = new Real();
        }
        if(moedaOrigemCB.getSelectedItem().toString().equals("Dólar")){
            moedaOrigem = new Dolar();
        }
        if(moedaOrigemCB.getSelectedItem().toString().equals("Euro ")){
            moedaOrigem = new Euro();
        }
        if(moedaOrigemCB.getSelectedItem().toString().equals("<Selecione>")){
            JOptionPane.showMessageDialog(rootPane, "Você deve selecionar uma moeda", "Selecione uma moeda", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_moedaOrigemCBActionPerformed
    
    private void validaEntrada(String entrada){
        String regex = "^\\d+(?:[,.]\\d+)?$";
            if (!valorTF.getText().matches(regex)){
                valorTF.setText("");
                JOptionPane.showMessageDialog(rootPane, "Valor inválido, tente novamente", "Erro", JOptionPane.ERROR_MESSAGE);
            }
    }
    
    private void valorTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTFActionPerformed
        validaEntrada(valorTF.getText());
    }//GEN-LAST:event_valorTFActionPerformed

    private void converterBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterBTActionPerformed
        if(moedaOrigemCB.getSelectedItem().toString().equals("<Selecione>")){
            
        }
    }//GEN-LAST:event_converterBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton converterBT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> moedaDestinoCB;
    private javax.swing.JComboBox<String> moedaOrigemCB;
    private javax.swing.JTextField resultadoTF1;
    private javax.swing.JTextField valorTF;
    // End of variables declaration//GEN-END:variables
}
